version: '3.2'

services:

  frontend:
    build: frontend
    ports:
      - 20081:80
    volumes:
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ./:/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_DATABASE: yii2advanced
      MYSQL_USER: yii2advanced
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_fresh:/var/lib/mysql

volumes:
  mysql_fresh: